- name: "Verify valid cluster name"
  ansible.builtin.assert:
    that: region_cluster_name is regex('^[a-z0-9]([-a-z0-9]*[a-z0-9])?$')
    fail_msg: "region_cluster_name failed regex validation"
    success_msg: "{{ region_cluster_name }} is valid"

- name: "Create regional ManagedCluster"
  kubernetes.core.k8s:
    state: present
    template: managedcluster.yml.j2

- name: Ensure regional cluster namespace has been created
  kubernetes.core.k8s_info:
    api: v1
    kind: Namespace
    name: "{{ region_cluster_name }}"
  register: _acm_namespace_status
  until:
    - _acm_namespace_status.resources | length > 0
  retries: 60
  delay: 10

# To import the spoke cluster to the hub cluster, we need to create
# a secret that contains the spoke cluster's kubeconfig.
# This requires a special formatting, including double line breaks
# and a correct indentation.
- name: Create autoimport secret
  block:
    - name: Get kubeconfig content
      ansible.builtin.slurp:
        src: "{{ SPOKECONFIG }}"
      register: _acm_region_kubeconfig_content
      no_log: true

    - name: Save kubeconfig content in a variable
      ansible.builtin.set_fact:
        acm_region_kubeconfig: "{{ _acm_region_kubeconfig_content['content'] | b64decode }}"
      no_log: true

    - name: Apply Secret to attach spoke cluster to hub cluster
      kubernetes.core.k8s:
        state: present
        definition: "{{ lookup('ansible.builtin.template', 'autoimport_secret.yml.j2') | from_yaml }}"
      no_log: true

# To correctly join the hub cluster, ManagedClusterJoined condition must be True.
- name: Ensure ManagedCluster has joined the hub cluster
  kubernetes.core.k8s_info:
    api: cluster.open-cluster-management.io/v1
    kind: ManagedCluster
    name: "{{ region_cluster_name }}"
  register: _acm_managedcluster_status
  vars:
    _acm_status_query: "resources[0].status.conditions[?type=='ManagedClusterJoined'].status"
    _acm_update_status: "{{ _acm_managedcluster_status | json_query(_acm_status_query) | flatten | unique }}"  # noqa: jinja[invalid]
  until:
    - _acm_managedcluster_status.resources is defined
    - _acm_managedcluster_status.resources | length > 0
    - _acm_update_status == ['True']
  retries: 30
  delay: 10

- name: "Create regional KlusterAddonConfig"
  kubernetes.core.k8s:
    state: present
    template: klusterletaddonconfig.yml.j2
